import { Router, type IRouter } from "express";
import { authMiddleware } from "../middlewares/authMiddleware";
import healthRouter from "./health";
import authRouter from "./auth";
import decksRouter from "./decks";
import cardsRouter from "./cards";
import generateRouter from "./generate";
import exportApkgRouter from "./export-apkg";
import extractPdfRouter from "./extract-pdf";
import extractOfficeRouter from "./extract-office";
import explainRouter from "./explain";
import transferRouter from "./transfer";
import generationsRouter from "./generations";
import downloadApkRouter from "./download-apk";
import qbanksRouter from "./qbanks";
import mindMapRouter from "./mind-map";
import deckMindMapsRouter from "./deck-mind-maps";
import feedbackRouter from "./feedback";
import topicsRouter from "./topics";
import subscriptionRouter from "./subscription";
import devRouter from "./dev";

const router: IRouter = Router();

router.use(authMiddleware);
router.use(healthRouter);
router.use(authRouter);
router.use(subscriptionRouter);
router.use(decksRouter);
router.use(cardsRouter);
router.use(generateRouter);
router.use(exportApkgRouter);
router.use(extractPdfRouter);
router.use(extractOfficeRouter);
router.use(explainRouter);
router.use(transferRouter);
router.use(generationsRouter);
router.use(downloadApkRouter);
router.use(qbanksRouter);
router.use(mindMapRouter);
router.use(deckMindMapsRouter);
router.use(feedbackRouter);
router.use(topicsRouter);
router.use(devRouter);

export default router;
